export const ELEMENTS = {
    pageHeadingH1:".page-heading",
    gender_radio:"#id_gender1[type=radio]",
    firstName_informations:"#customer_firstname",
    lastName_informations:"#customer_lastname",
    email:"#email",
    password:"#passwd",
    birthDate_day:"#days",
    birthDate_months:"#months",
    birthDate_years:"#years",
    firstName_adress: "#firstname[type=text]",
    lastName_adress: "#lastname[type=text]",
    company_input: "#company",
    address_input: "#address1",
    addressComplement_input: "#address2",
    city_input: "#city",
    state_select: "#id_state",
    postCode_input: "#postcode",
    country_select: "#id_country",
    aditionlInformation_input: "#other",
    homePhone_input: "#phone",
    mobilePhone_input: "#phone_mobile",
    alias_input: "#alias",
    submitButton: "#submitAccount"
}